export const INITIAL_PRODUCTS = [
  {
    id: 'prod_1',
    title: 'Professional 7-Speed Stand Mixer – Titanium Silver',
    slug: 'professional-7-speed-stand-mixer-titanium-silver',
    category: 'Electronics',
    subCategory: 'Mixers & Blenders',
    description: 'High-torque 800W motor engineered for heavy bread dough and delicate airy meringues. Includes 4.8L stainless steel bowl, dough hook, wire whisk, and flex-edge beater.',
    shortDescription: '800W high-torque stand mixer with 4.8L stainless steel bowl.',
    price: 14999.00,
    compareAtPrice: 18500.00,
    sku: 'ELEC-MIX-001',
    warehouseStock: 45,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.9,
    reviewCount: 184,
    images: [{ url: 'https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=800', alt: 'Stand Mixer' }],
    tags: ['stand-mixer', 'electronics', 'baking']
  },
  {
    id: 'prod_2',
    title: 'Ultra-Precision Digital Kitchen Scale (0.1g Accuracy)',
    slug: 'ultra-precision-digital-kitchen-scale',
    category: 'Electronics',
    subCategory: 'Scales & Thermometers',
    description: 'Essential for artisan sourdough, macarons, and pastry measurements. Reads down to 0.1g increments with tare function and backlit LCD display.',
    shortDescription: '0.1g high-precision digital scale with stainless steel surface.',
    price: 1450.00,
    compareAtPrice: 1800.00,
    sku: 'ELEC-SCALE-002',
    warehouseStock: 120,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.8,
    reviewCount: 92,
    images: [{ url: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800', alt: 'Scale' }],
    tags: ['scale', 'precision', 'electronics']
  },
  {
    id: 'prod_3',
    title: 'Infrared Laser Food & Oven Surface Thermometer',
    slug: 'infrared-laser-food-thermometer',
    category: 'Electronics',
    subCategory: 'Scales & Thermometers',
    description: 'Non-contact laser thermometer for measuring baking stone temperature, chocolate tempering, and hot sugar syrups accurately within 0.5 seconds.',
    shortDescription: 'Instant laser temperature gun with -50°C to 550°C range.',
    price: 2200.00,
    compareAtPrice: 2800.00,
    sku: 'ELEC-THERM-003',
    warehouseStock: 65,
    isAvailable: true,
    isFeatured: false,
    averageRating: 4.7,
    reviewCount: 45,
    images: [{ url: 'https://images.unsplash.com/photo-1584282479904-54c3cf7b2355?w=800', alt: 'Thermometer' }],
    tags: ['thermometer', 'laser', 'electronics']
  },
  {
    id: 'prod_4',
    title: 'Premium Silicone Macaron Baking Mat (Set of 2)',
    slug: 'premium-silicone-macaron-baking-mat-set-of-2',
    category: 'BakingTools',
    subCategory: 'Molds & Mats',
    description: 'Heat-resistant platinum silicone mats with printed concentric guide rings for piping perfectly uniform French macarons, eclairs, and cookies.',
    shortDescription: 'Food-grade non-stick silicone mats with piping circles.',
    price: 650.00,
    compareAtPrice: 850.00,
    sku: 'TOOL-MAT-004',
    warehouseStock: 180,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.9,
    reviewCount: 210,
    images: [{ url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800', alt: 'Macaron Mats' }],
    tags: ['macaron', 'silicone-mat', 'baking-tools']
  },
  {
    id: 'prod_5',
    title: '52-Piece Stainless Steel Piping Nozzles & Bag Kit',
    slug: '52-piece-stainless-steel-piping-nozzles-kit',
    category: 'BakingTools',
    subCategory: 'Decorating Tools',
    description: 'Complete cake decorating kit featuring Russian piping tips, leaf nozzles, star tips, flower nails, coupler adapters, and reusable pastry bags.',
    shortDescription: '52-piece professional cake decorating nozzle kit with case.',
    price: 1250.00,
    compareAtPrice: 1600.00,
    sku: 'TOOL-PIP-005',
    warehouseStock: 95,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.8,
    reviewCount: 140,
    images: [{ url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800', alt: 'Piping Tips' }],
    tags: ['piping-nozzles', 'cake-decorating']
  },
  {
    id: 'prod_6',
    title: 'Heavy-Duty Aluminum Revolving Cake Turntable',
    slug: 'heavy-duty-aluminum-revolving-cake-turntable',
    category: 'BakingTools',
    subCategory: 'Decorating Tools',
    description: '12-inch cast aluminum rotating cake stand with ultra-smooth dual ball bearings and non-slip rubber silicone base.',
    shortDescription: '12-inch heavy-duty aluminum revolving turntable.',
    price: 2400.00,
    compareAtPrice: 3000.00,
    sku: 'TOOL-TURN-006',
    warehouseStock: 40,
    isAvailable: true,
    isFeatured: false,
    averageRating: 4.9,
    reviewCount: 68,
    images: [{ url: 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=800', alt: 'Turntable' }],
    tags: ['turntable', 'cake-decorating']
  },
  {
    id: 'prod_7',
    title: 'Artisan San Francisco Sourdough Boule (850g)',
    slug: 'artisan-san-francisco-sourdough-boule',
    category: 'Bakery',
    subCategory: 'Artisan Breads',
    description: 'Slow-fermented for 36 hours using our 10-year-old sourdough mother culture. Blistered golden crust, open airy crumb, and a deeply aromatic tangy flavor.',
    shortDescription: '36-hour slow fermented wild sourdough boule baked on stone.',
    price: 380.00,
    sku: 'BAKE-BREAD-007',
    warehouseStock: 30,
    isAvailable: true,
    isFeatured: true,
    averageRating: 5.0,
    reviewCount: 310,
    images: [{ url: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=800', alt: 'Sourdough Bread' }],
    tags: ['sourdough', 'bread', 'bakery']
  },
  {
    id: 'prod_8',
    title: 'French Pure Butter Croissant (Box of 4)',
    slug: 'french-pure-butter-croissant-box-of-4',
    category: 'Bakery',
    subCategory: 'Pastries & Croissants',
    description: 'Crafted with 82% Normandy cultured butter. 27 delicate lamination layers yielding a honeycomb interior and crisp flaky exterior.',
    shortDescription: 'Traditional French lamination with Normandy butter.',
    price: 520.00,
    sku: 'BAKE-PAST-008',
    warehouseStock: 50,
    isAvailable: true,
    isFeatured: true,
    averageRating: 4.9,
    reviewCount: 195,
    images: [{ url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800', alt: 'Croissants' }],
    tags: ['croissant', 'french-pastry', 'bakery']
  },
  {
    id: 'prod_9',
    title: 'Belgian Dark Chocolate Ganache Gateau (1 kg)',
    slug: 'belgian-dark-chocolate-ganache-gateau',
    category: 'Bakery',
    subCategory: 'Cakes & Gateaux',
    description: 'Moist cocoa sponge layered with 70% Callebaut dark chocolate whipped ganache and glazed with glossy dark mirror glaze.',
    shortDescription: 'Rich 70% Belgian chocolate cake with mirror glaze.',
    price: 1850.00,
    sku: 'BAKE-CAKE-009',
    warehouseStock: 20,
    isAvailable: true,
    isFeatured: true,
    averageRating: 5.0,
    reviewCount: 280,
    images: [{ url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800', alt: 'Chocolate Cake' }],
    tags: ['cake', 'chocolate', 'gateau']
  }
];

export const INITIAL_TUTORIALS = [
  {
    id: 'tut_1',
    title: 'Mastering French Macarons & Ganache Fillings',
    slug: 'mastering-french-macarons-ganache-fillings',
    category: 'Pastry & Macarons',
    skillLevel: 'Intermediate',
    durationMinutes: 45,
    description: 'A complete 45-minute masterclass covering the Italian meringue method for foolproof macarons. Learn precise macaronage technique, resting times, and 3 signature ganache recipes.',
    instructor: {
      name: 'Chef Aminul Haque',
      bio: 'Executive Pastry Chef with 15 years experience in Parisian patisseries.',
      avatarUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150'
    },
    thumbnail: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    accessType: 'SubscriberOnly',
    viewCount: 8420,
    averageRating: 4.9,
    ingredients: [
      '200g Extra-fine Almond Flour',
      '200g Confectioner\'s Sugar',
      '150g Aged Egg Whites',
      '150g Granulated Sugar',
      '200g Callebaut 70% Dark Chocolate'
    ],
    chapters: [
      { timestampSeconds: 0, timestampDisplay: '00:00', title: 'Course Overview & Ingredient Science' },
      { timestampSeconds: 135, timestampDisplay: '02:15', title: 'Preparing Italian Meringue & Sugar Syrup' },
      { timestampSeconds: 940, timestampDisplay: '15:40', title: 'The Macaronage Technique (Folding to Lava Flow)' },
      { timestampSeconds: 1690, timestampDisplay: '28:10', title: 'Piping, Tapping, and Skin Formation' },
      { timestampSeconds: 2280, timestampDisplay: '38:00', title: 'Baking & Dark Chocolate Ganache Assembly' }
    ]
  },
  {
    id: 'tut_2',
    title: 'The Ultimate Wild Sourdough Bread Guide',
    slug: 'the-ultimate-wild-sourdough-bread-guide',
    category: 'Artisan Breads',
    skillLevel: 'Beginner',
    durationMinutes: 60,
    description: 'Learn how to build a vigorous sourdough starter, calculate baker\'s percentages, perform coil folds, score decorative patterns, and bake with steam.',
    instructor: {
      name: 'Chef Aminul Haque',
      bio: 'Master Baker & Sourdough Fermentation Specialist.',
      avatarUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150'
    },
    thumbnail: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    accessType: 'SubscriberOnly',
    viewCount: 12500,
    averageRating: 5.0,
    ingredients: [
      '500g High-Protein Bread Flour (13%)',
      '375g Filtered Water (75% hydration)',
      '100g Active Sourdough Starter',
      '10g Fine Sea Salt'
    ],
    chapters: [
      { timestampSeconds: 0, timestampDisplay: '00:00', title: 'Understanding Wild Yeast & Levain Build' },
      { timestampSeconds: 300, timestampDisplay: '05:00', title: 'Autolyse & Dough Mixing' },
      { timestampSeconds: 1200, timestampDisplay: '20:00', title: 'Bulk Fermentation & Coil Folds' },
      { timestampSeconds: 2400, timestampDisplay: '40:00', title: 'Pre-shaping & Final Banneton Shaping' },
      { timestampSeconds: 3100, timestampDisplay: '51:40', title: 'Lame Scoring & Dutch Oven Baking' }
    ]
  },
  {
    id: 'tut_3',
    title: 'Modern Buttercream Palette Knife Cake Artistry',
    slug: 'modern-buttercream-palette-knife-cake-artistry',
    category: 'Cake Artistry',
    skillLevel: 'Advanced',
    durationMinutes: 50,
    description: 'Transform standard frosted cakes into painterly canvases using Swiss meringue buttercream, artist palette knives, and natural botanical color palettes.',
    instructor: {
      name: 'Elena Rostova',
      bio: 'International Cake Sculptor & Floral Buttercream Pioneer.',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150'
    },
    thumbnail: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    accessType: 'SubscriberOnly',
    viewCount: 6100,
    averageRating: 4.9,
    ingredients: [
      '300g Egg Whites',
      '500g Granulated Sugar',
      '680g European Unsalted Butter',
      '10ml Pure Vanilla Bean Extract',
      'Gel Food Pigments'
    ],
    chapters: [
      { timestampSeconds: 0, timestampDisplay: '00:00', title: 'Preparing Stable Swiss Meringue Buttercream' },
      { timestampSeconds: 480, timestampDisplay: '08:00', title: 'Color Blending with Gel and Oil Pigments' },
      { timestampSeconds: 1500, timestampDisplay: '25:00', title: 'Palette Knife Petal Techniques' },
      { timestampSeconds: 2520, timestampDisplay: '42:00', title: 'Texturing, Gold Leaf, and Final Presentation' }
    ]
  }
];
